FROM ubuntu:22.04 
RUN apt-get update -y \ 
    && apt-get install -y python-setuptools python3-pip

ENV GREETING="Summer is here!"
ADD requirements.txt /src/requirements.txt
RUN cd /src; pip install -r requirements.txt
ADD . /src
WORKDIR /src
EXPOSE 5001 							

# Add environment variable GREETING with value "Summer is here."
CMD ["python3", "/src/application.py"]
